server:
  port: 0

spring:
  application:
    name: clientes
  
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca_MS1?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /clientes/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/biblioteca_MS1_dev?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update # Permitimos que actualice localmente si es necesario

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/biblioteca_MS1_test?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/biblioteca_MS1_prod?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: none
