server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                exposed-headers: "*"
                allow-credentials: false
                max-age: 3600

          routes:
            # Separacion al MS1

            - id: clientes-service
              uri: lb://clientes
              predicates:
                - Path=/api/v1/clientes/**, /clientes/api-docs/**

            - id: prestamos-service
              uri: lb://clientes
              predicates:
                - Path=/api/v1/prestamos/**, /prestamos/api-docs/**

            # Separacion al MS2

            - id: empleados-service
              uri: lb://empleados
              predicates:
                - Path=/api/v1/empleados/**, /empleados/api-docs/**

            - id: contratos-service
              uri: lb://empleados
              predicates:
                - Path=/api/v1/contratos/**, /contratos/api-docs/**

            # Separacion al MS3

            - id: regiones-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/regiones/**, /regiones/api-docs/**

            - id: comunas-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/comunas/**, /comunas/api-docs/**

            - id: bibliotecas-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/bibliotecas/**, /bibliotecas/api-docs/**

            # Separacion al MS4

            - id: libros-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/libros/**, /libros/api-docs/**

            - id: categorias-service
              uri: lb://libros
              predicates:  
              - Path=/api/v1/categorias/**, /categorias/api-docs/**

            - id: autores-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/autores/**, /autores/api-docs/**

            - id: editoriales-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/editoriales/**, /editoriales/api-docs/**
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
    - name: Microservicio Clientes
      url: /clientes/api-docs
    - name: Microservicio Préstamos
      url: /prestamos/api-docs

    - name: Microservicio Empleados
      url: /empleados/api-docs
    - name: Microservicio Contratos
      url: /contratos/api-docs

    - name: Microservicio Regiones
      url: /regiones/api-docs
    - name: Microservicio Comunas
      url: /comunas/api-docs
    - name: Microservicio Bibliotecas
      url: /bibliotecas/api-docs

    - name: Microservicio Libros
      url: /libros/api-docs
    - name: Microservicio Categorías
      url: /categorias/api-docs
    - name: Microservicio Autores
      url: /autores/api-docs
    - name: Microservicio Editoriales
      url: /editoriales/api-docs
      
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
