server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Separacion al MS1

            - id: clientes-service
              uri: lb://clientes
              predicates:
                - Path=/api/v1/clientes/**

            - id: prestamos-service
              uri: lb://clientes
              predicates:
                - Path=/api/v1/prestamos/**

            # Separacion al MS2

            - id: empleados-service
              uri: lb://empleados
              predicates:
                - Path=/api/v1/empleados/**

            - id: contratos-service
              uri: lb://empleados
              predicates:
                - Path=/api/v1/contratos/**

            # Separacion al MS3

            - id: regiones-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/regiones/**

            - id: comunas-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/comunas/**

            - id: bibliotecas-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/bibliotecas/**

            # Separacion al MS4

            - id: libros-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/libros/**

            - id: categorias-service
              uri: lb://libros
              predicates:  
              - Path=/api/v1/categorias/**

            - id: autores-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/autores/**

            - id: editoriales-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/editoriales/**
