server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # Separacion al MS1

            - id: clientes-service
              uri: lb://clientes
              predicates:
                - Path=/api/v1/clientes/**, /clientes/api-docs/**

            - id: prestamos-service
              uri: lb://clientes
              predicates:
                - Path=/api/v1/prestamos/**, /prestamos/api-docs/**

            # Separacion al MS2

            - id: empleados-service
              uri: lb://empleados
              predicates:
                - Path=/api/v1/empleados/**, /empleados/api-docs/**

            - id: contratos-service
              uri: lb://empleados
              predicates:
                - Path=/api/v1/contratos/**, /contratos/api-docs/**

            # Separacion al MS3

            - id: regiones-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/regiones/**, /regiones/api-docs/**

            - id: comunas-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/comunas/**, /comunas/api-docs/**

            - id: bibliotecas-service
              uri: lb://bibliotecas
              predicates:
                - Path=/api/v1/bibliotecas/**, /bibliotecas/api-docs/**

            # Separacion al MS4

            - id: libros-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/libros/**, /libros/api-docs/**

            - id: categorias-service
              uri: lb://libros
              predicates:  
              - Path=/api/v1/categorias/**, /categorias/api-docs/**

            - id: autores-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/autores/**, /autores/api-docs/**

            - id: editoriales-service
              uri: lb://libros
              predicates:
              - Path=/api/v1/editoriales/**, /editoriales/api-docs/**
